<a href="https://colab.research.google.com/github/Iam-Divyesh/Diabetes-Classifier/blob/main/Diabetes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
!pip install -q kaggle

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/KaggleCredentials/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [11]:
!kaggle datasets download -d uciml/pima-indians-diabetes-database

Dataset URL: https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database
License(s): CC0-1.0

In [12]:
!unzip pima-indians-diabetes-database.zip -d ./pima_data

Archive:  pima-indians-diabetes-database.zip
  inflating: ./pima_data/diabetes.csv

In [14]:
#importing necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [19]:
df = pd.read_csv('./pima_data/diabetes.csv')

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [18]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
df[(df['BloodPressure'] >= 0) & (df['BloodPressure'] <=40)]

### **It is Not possible someone having 0 Blood Pressure**
so that i am removing all that related data

In [27]:
df[df['BloodPressure'] == 0].shape

(35, 9)

In [28]:
df.shape

(768, 9)

In [31]:
df1 = df[df['BloodPressure'] != 0]

In [32]:
df1.shape

(733, 9)

In [34]:
df1.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,733.000000,733.000000,733.000000,733.000000,733.000000,733.000000,733.000000,733.000000,733.000000
mean,3.855389,121.042292,72.405184,21.444748,83.609823,32.292769,0.475861,33.361528,0.343793
std,3.358106,32.179943,12.382158,15.705756,116.606997,7.271540,0.334179,11.837077,0.475297
min,0.000000,0.000000,24.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,0.000000,0.000000,27.400000,0.245000,24.000000,0.000000
50%,3.000000,117.000000,72.000000,24.000000,45.000000,32.300000,0.380000,29.000000,0.000000
75%,6.000000,141.000000,80.000000,33.000000,130.000000,36.600000,0.629000,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [39]:
df2 = df1[df1['Glucose'] != 0]
df3 = df2[df2['BMI'] != 0]

### **Modle Training**

In [41]:
# Spliting Data for training and testing
from sklearn.model_selection import train_test_split
X = df3.drop('Outcome', axis=1)
y = df3['Outcome']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [43]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()

In [45]:
logistic.fit(X_train , y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [46]:
y_pred = logistic.predict(X_test)

In [47]:
from sklearn.metrics import accuracy_score, classification_report , confusion_matrix

In [50]:
score = accuracy_score(y_test , y_pred)
print(score)
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

0.7740585774058577
[[142  17]
 [ 37  43]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       159
           1       0.72      0.54      0.61        80

    accuracy                           0.77       239
   macro avg       0.75      0.72      0.73       239
weighted avg       0.77      0.77      0.76       239

### **Hyperparameter Tuning**
GridSearchCv and StratifiedSearchCv

In [51]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

penalty = ['l1', 'l2', 'elasticnet']

c_values = [100,10,1.0,0.1,0.01]

solver = ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']

params = dict(penalty = penalty , C = c_values , solver = solver)

grid = GridSearchCV(estimator=logistic , param_grid=params ,scoring='accuracy' ,cv = cv , n_jobs=-1 )

In [ ]:
grid.fit(X_train , y_train)

In [53]:
grid.best_params_

{'C': 1.0, 'penalty': 'l1', 'solver': 'liblinear'}

In [54]:
y_pred = grid.predict(X_test)

In [55]:
score = accuracy_score(y_test , y_pred)
print(score)
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

0.7698744769874477
[[140  19]
 [ 36  44]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       159
           1       0.70      0.55      0.62        80

    accuracy                           0.77       239
   macro avg       0.75      0.72      0.73       239
weighted avg       0.76      0.77      0.76       239

In [56]:
from sklearn.model_selection import RandomizedSearchCV

In [57]:
model = LogisticRegression()

randomcv = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    cv = 5,
    scoring= 'accuracy'
)

In [ ]:
randomcv.fit(X_train , y_train)

In [60]:
y_pred = randomcv.predict(X_test)

In [61]:
score = accuracy_score(y_test , y_pred)
print(score)
print(confusion_matrix(y_test , y_pred))
print(classification_report(y_test , y_pred))

0.7740585774058577
[[142  17]
 [ 37  43]]
              precision    recall  f1-score   support

           0       0.79      0.89      0.84       159
           1       0.72      0.54      0.61        80

    accuracy                           0.77       239
   macro avg       0.75      0.72      0.73       239
weighted avg       0.77      0.77      0.76       239

In [63]:
df3.sample(1)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
432,1,80,74,11,60,30.0,0.527,22,0

In [76]:
new_df = pd.DataFrame({
    'Pregnancies': [1],
    'Glucose': [150],
    'BloodPressure': [74],
    'SkinThickness': [20],
    'Insulin': [60],
    'BMI': [30.0],
    'DiabetesPedigreeFunction': [0.700],
    'Age': [22]
})

In [66]:
def predict_diabetes(df):
  prediction = randomcv.predict(df)
  return prediction

In [77]:
predict_diabetes(new_df)

array([1])